### ISSUE TITLE
[FR]: Request that regular expressions be provided in text replacer

### ISSUE THREAD

**Issue by Olintary** [Lisandra-dev/copy-reading-in-markdown#3]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Is your feature related to a problem ?

The plugin works great.But the text replacer function can only replace fixed text, can you provide the function of entering regular expressions? thanks.

### What solution do you want to see ?

Added regular expression text replacement function.

### OS

Windows

### Obsidian information

```bash session
Without.
```

### Plugin version

0.2.12

**Comment by Mara-Li** [comment]
But it does! If enclosed in `//`
